# Generated by Django 5.2.6 on 2025-09-13 19:08

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackgroundBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("photo", "Фото на фоні"), ("color", "Просто фон")],
                        default="color",
                        max_length=20,
                        verbose_name="Тип фону",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banners/backgrounds/",
                        verbose_name="Фонове зображення",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cinema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("condition", models.TextField(blank=True)),
                (
                    "logo_cinema",
                    models.ImageField(blank=True, null=True, upload_to="cinema_logos/"),
                ),
                (
                    "banner_cinema",
                    models.ImageField(
                        blank=True, null=True, upload_to="cinema_banners/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cinema",
                "verbose_name_plural": "Cinemas",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Contact Page",
                "verbose_name_plural": "Contact Pages",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="ImageTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SeoBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(db_index=True, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("keywords", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Seo Block",
                "verbose_name_plural": "Seo Blocks",
                "db_table": "seo_block",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("coordinates", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="contact_logos/"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="admin_panel.contactpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo_hall",
                    models.ImageField(blank=True, null=True, upload_to="hall_logos/"),
                ),
                (
                    "banner_hall",
                    models.ImageField(blank=True, null=True, upload_to="hall_banners/"),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="halls",
                        to="admin_panel.cinema",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="halls",
                        to="admin_panel.imagetitle",
                    ),
                ),
                (
                    "seo_hall",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="halls",
                        to="admin_panel.seoblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hall",
                "verbose_name_plural": "Halls",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("text", models.CharField(max_length=200)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="admin_panel.imagetitle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "film_image",
                    models.ImageField(blank=True, null=True, upload_to="films/"),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "type_show",
                    models.IntegerField(
                        choices=[(0, "Poster"), (1, "In While")], default=0
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        choices=[("2D", "2D"), ("3D", "3D"), ("IMAX", "IMAX")],
                        default="2D",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="films",
                        to="admin_panel.imagetitle",
                    ),
                ),
                (
                    "seo_film",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="films",
                        to="admin_panel.seoblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
                "db_table": "film",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="cinema",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cinemas",
                to="admin_panel.imagetitle",
            ),
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("main", "Головний"), ("news", "Новини")],
                        default="main",
                        max_length=20,
                        verbose_name="Тип банера",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубліковано"),
                ),
                (
                    "rotation_speed",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Швидкість ротації (сек)",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="admin_panel.imagetitle",
                        verbose_name="Колекція зображень",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "format_type",
                    models.CharField(
                        choices=[("2D", "2D"), ("DBOX", "DBOX"), ("VIP", "VIP")],
                        default="2D",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seances",
                        to="admin_panel.film",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seances",
                        to="admin_panel.hall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seance",
                "verbose_name_plural": "Seances",
                "ordering": ["datetime"],
            },
        ),
        migrations.CreateModel(
            name="SecondPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="second_page_images/"
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_pages",
                        to="admin_panel.imagetitle",
                    ),
                ),
                (
                    "seo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_pages",
                        to="admin_panel.seoblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Second Page",
                "verbose_name_plural": "Second Pages",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="news/")),
                ("is_published", models.BooleanField(default=False)),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("link_url", models.URLField(blank=True, null=True)),
                (
                    "type_page",
                    models.IntegerField(
                        choices=[(0, "Action"), (1, "News")], default=1
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="admin_panel.imagetitle",
                    ),
                ),
                (
                    "seo_news",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="admin_panel.seoblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="MainPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "phone_primary",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "phone_secondary",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("seo_description", models.TextField(blank=True, null=True)),
                (
                    "seo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_pages",
                        to="admin_panel.seoblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main Page",
                "verbose_name_plural": "Main Pages",
                "ordering": ["-published_date"],
            },
        ),
        migrations.AddField(
            model_name="contactpage",
            name="seo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_pages",
                to="admin_panel.seoblock",
            ),
        ),
        migrations.AddField(
            model_name="cinema",
            name="seo_cinema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cinemas",
                to="admin_panel.seoblock",
            ),
        ),
    ]
