# Generated by Django 5.2.6 on 2025-09-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
