# Generated by Django 5.2.6 on 2025-09-27 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_alter_galleryimage_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="seance",
            name="cinema",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seances",
                to="admin_panel.cinema",
            ),
            preserve_default=False,
        ),
    ]
