# Generated by Django 5.2.6 on 2025-09-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_seance_cinema"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundbanner",
            name="background_color",
            field=models.CharField(
                blank=True,
                help_text="Вкажіть HEX-код або назву кольору (наприклад: #ffffff або red)",
                max_length=20,
                null=True,
                verbose_name="Колір фону",
            ),
        ),
    ]
